### ISSUE TITLE
Check out my repo already!

### ISSUE THREAD

**Issue by kutsan** [kuator/awesome-dotfiles#1]
> * [kutsan](https://github.com/kutsan/dotfiles) : didn't check out yet

It's like that for 2 months.

**Comment by kuator** [comment]
I'm really sorry, I didn't even notice that you wrote the issue. :scream:

**Comment by kutsan** [comment]
You know what to do since now you do. :3

**Comment by kuator** [comment]
> You know what to do since now you do. :3

:joy:

**Comment by kutsan** [comment]
Thanks by the way, have a good day/night. ^^
